# Generated by Django 5.1.4 on 2024-12-21 01:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('GE', 'General English'), ('EE', 'Extreme English')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.course')),
            ],
            options={
                'verbose_name_plural': 'Classes',
                'ordering': ['start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('participation', models.TextField(blank=True)),
                ('teacher_comments', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('current_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='records.class')),
            ],
            options={
                'ordering': ['student_id'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(to='records.teacher'),
        ),
        migrations.CreateModel(
            name='NumericAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('G', 'Grammar'), ('V', 'Vocabulary'), ('L', 'Listening'), ('R', 'Reading'), ('W', 'Writing'), ('S', 'Speaking'), ('P', 'Pronunciation')], max_length=1)),
                ('week', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('status', models.CharField(choices=[('COM', 'Completed'), ('NA', 'Not Given'), ('HOL', 'Holiday'), ('ABS', 'Absent'), ('DNS', 'Did Not Submit')], default='COM', max_length=3)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_questions', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('correct_answers', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_submissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.student')),
            ],
            options={
                'unique_together': {('student', 'skill', 'week')},
            },
        ),
        migrations.CreateModel(
            name='GradedAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('G', 'Grammar'), ('V', 'Vocabulary'), ('L', 'Listening'), ('R', 'Reading'), ('W', 'Writing'), ('S', 'Speaking'), ('P', 'Pronunciation')], max_length=1)),
                ('week', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('status', models.CharField(choices=[('COM', 'Completed'), ('NA', 'Not Given'), ('HOL', 'Holiday'), ('ABS', 'Absent'), ('DNS', 'Did Not Submit')], default='COM', max_length=3)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('grade', models.CharField(blank=True, choices=[('A', 'A - Excellent'), ('B', 'B - Good'), ('C', 'C - Developing'), ('D', 'D - Needs Improvement'), ('E', 'E - Unsatisfactory')], max_length=1, null=True)),
                ('comments', models.TextField(blank=True)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_submissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.student')),
            ],
            options={
                'unique_together': {('student', 'skill', 'week')},
            },
        ),
    ]
