# Generated by Django 5.1.4 on 2024-12-21 08:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradedassessment',
            name='skill',
            field=models.CharField(choices=[('W', 'Writing'), ('S', 'Speaking'), ('P', 'Pronunciation')], db_column='skill', max_length=1),
        ),
        migrations.AlterField(
            model_name='numericassessment',
            name='skill',
            field=models.CharField(choices=[('G', 'Grammar'), ('V', 'Vocabulary'), ('L', 'Listening'), ('R', 'Reading')], db_column='skill', max_length=1),
        ),
        migrations.AddIndex(
            model_name='numericassessment',
            index=models.Index(fields=['student', 'skill', 'week'], name='records_num_student_0ae19f_idx'),
        ),
        migrations.AddIndex(
            model_name='numericassessment',
            index=models.Index(fields=['skill', 'week'], name='records_num_skill_298458_idx'),
        ),
    ]
