# Generated by Django 5.1.4 on 2024-12-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_gradedassessment_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradedassessment',
            name='skill',
            field=models.CharField(choices=[('W', 'Writing'), ('S', 'Speaking'), ('P', 'Pronunciation')], max_length=1),
        ),
        migrations.AlterField(
            model_name='numericassessment',
            name='skill',
            field=models.CharField(choices=[('G', 'Grammar'), ('V', 'Vocabulary'), ('L', 'Listening'), ('R', 'Reading')], max_length=1),
        ),
    ]
