# Generated by Django 5.1.4 on 2024-12-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_gradedassessment_skill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradedassessment',
            name='comments',
        ),
        migrations.AddField(
            model_name='numericassessment',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
